Repository MetaMask/keyring-api, pull requests merged in 2023-10, with the labels that each got.

#142 docs: remove some bad code from examples
  README.md
Labels: team-accounts, high-priority, type-documentation

#139 refactor!: change the events' prefix to `notify:`
  src/events.ts
Labels: team-accounts, type-enhancement, high-priority

#145 feat!: use the `onKeyringRequest` snap export
  package.json
  src/KeyringSnapControllerClient.test.ts
  src/KeyringSnapControllerClient.ts
  src/KeyringSnapRpcClient.test.ts
  src/KeyringSnapRpcClient.ts
  yarn.lock
Labels: team-accounts, type-enhancement, high-priority

#175 deps: migrate from @metamask/rpc-methods to @metamask/snaps-rpc-methods
  package.json
  src/snap-utils.ts
  yarn.lock
Labels: type-dependencies
